trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo "Running app build steps"
  displayName: 'Build App'

- task: Docker@2
  inputs:
    containerRegistry: 'your-docker-service-connection'
    repository: 'your-dockerhub-username/devops-flask-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

